name: docker-actions

on:
  push:
    branches:
      - 'master'

env:
  REGISTRY: hub.docker.com
  IMAGE: rgherdt/sagittarius

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/sagittarius:0
        id: docker_build_0
        uses: docker/build-push-action@v2
        with:
          registry: ${{ REGISTRY }}
          push: true
          context: 0/
          tags: |
            ${{ IMAGE }}:0
            ${{ IMAGE }}:0-bullseye-slim
            ${{ IMAGE }}:latest

        name: Build and push schemers/sagittarius:head
        id: docker_build_head
        uses: docker/build-push-action@v2
        with:
          registry: ${{ REGISTRY }}
          push: true
          context: head/
          tags: |
            ${{ IMAGE }}:head
            ${{ IMAGE }}:head-bullseye-slim
