name: docker-actions

on:
  push:
    branches:
      - 'master'

  jobs:
    docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push schemers/sagittarius:0
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: rgherdt/sagittarius:0-bullseye-slim rgherdt/sagittarius:0 rgherdt/sagittarius:latest
            file: 0/Dockerfile
        -
          name: Build and push schemers/sagittarius:head
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: rgherdt/sagittarius:head-bullseye-slim rgherdt/sagittarius:head
            file: head/Dockerfile
