name: docker-actions

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push schemers/sagittarius:0
        id: docker_build_0
        uses: docker/build-push-action@v2
        with:
          push: true
          image: rgherdt/sagittarius
          directory: 0/
          file: 0/Dockerfile
          tags: 0, 0-bullseye-slim, latest
      -
        name: Build and push schemers/sagittarius:head
        id: docker_build_head
        uses: docker/build-push-action@v2
        with:
          push: true
          image: rgherdt/sagittarius
          tags: head, head-bullseye-slim
          directory: head/
          file: head/Dockerfile
